### ISSUE TITLE
https://github.com/laraveladmin-cn

### ISSUE THREAD

**Issue by laraveladmin-cn** [yuxingfei/laravel-admin#16]
我也做了个类型是功能:
项目地址[https://gitee.com/laravel-admin/laraveladmin](https://gitee.com/laravel-admin/laraveladmin)
官网[https://www.laraveladmin.cn/](https://www.laraveladmin.cn/)

**Comment by xpxw** [comment]
一个后台，不知道为什么非要搞成前后端分离的。
